In [2]:
a=5

In [3]:
b=5

In [7]:
c=a+b

# 문서
## 제목
### 소제목
- 하이픈은 불렛
- 계속 나열
 - 다음
 - 다음
 > 들여쓰기
   여러줄 문서작업 시 스페이스 두칸  
   다음줄

In [8]:
print(c)

10


In [11]:
# 정수, 실수, 문자열, 불리언
x=3
a = 0.1
b = 'Hello'
c = True
d = False

In [16]:
print(x + a + d + c)
print(x)

4.1
3


In [19]:
#[] 사용되는 경우 : list, index
x = [1,2,3,4,5]

In [20]:
type(x)

list

In [21]:
x * 3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [23]:
[i * 3 for i in x]

[3, 6, 9, 12, 15]

In [24]:
[i*i for i in x]

[1, 4, 9, 16, 25]

In [26]:
y = range(10)
y

range(0, 10)

In [27]:
[i*i for i in y]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [28]:
y = range(1,10,2)

In [29]:
print(y)

range(1, 10, 2)


In [32]:
for i in range(1,10,2):
    print(i*2)

2
6
10
14
18


In [33]:
z = range(1,4,0.1)

TypeError: 'float' object cannot be interpreted as an integer

In [34]:
import numpy as np

In [38]:
y = np.arange(1,2,0.2)
y

array([ 1. ,  1.2,  1.4,  1.6,  1.8])

In [39]:
y.shape

(5,)

In [50]:
y = np.arange(12); y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
y.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
y1 = y.reshape(3,4)

In [44]:
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
y = y1

In [46]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
y.shape

(3, 4)

In [48]:
#colume 은  features , row 는 sample을 의미

In [54]:
y = y.reshape(2,2,3)

In [58]:
y.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [59]:
y.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [61]:
# 튜플 (상수처럼 고정됨)
(a, b) = (4, 5) 

In [64]:
x = [4,3,6,7,1]
x[2]

6

In [66]:
x[2] = 1000
x[2]
x

[4, 3, 1000, 7, 1]

In [69]:
# 튜플
y = (4,3,6,7,1)
y[2]

6

In [70]:
y[2] = 100

TypeError: 'tuple' object does not support item assignment

In [73]:
# 딕셔너리
x = {'name':'kim', 'age':21, 'sex':'Male'}

In [74]:
x.keys()

dict_keys(['name', 'age', 'sex'])

In [76]:
x.values()

dict_values(['kim', 21, 'Male'])

In [2]:
import pandas as pd

In [78]:
pd.DataFrame(x)

ValueError: If using all scalar values, you must pass an index

In [1]:
x1 = {'name':['kim'], 'age':[21], 'sex':['Male']}

In [4]:
pd.DataFrame(x1)

age name   sex
0   21  kim  Male